### ISSUE TITLE
Support $exists with false

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1027]
Refactoring in the #981 allowed now to support `$exists` filter op with the `false` value. It would allow to check if the field is not existing in a document.

**Comment by ivansenic** [comment]
@EricBorczuk @dimas-b Can you help me out a bit. 

I the old implementation we allowed not equal checks with nulls (`"$ne": null`), however in the new implementation this is not supported (seems like a bug). However, since the other ops (`$eq, $gt, $gte, $lt, $lte`) do not support `null` as filter value, would it be fine if we simply implement this issue and keep `$ne` not supporting the nulls. It would be kind a breaking change. Or do we want to actually support both, exists with false and not equals with nulls, which is essentially the same. Or?

**Comment by dimas-b** [comment]
I'd say since `$eq: null` is not supported (user error, I assume), it makes sense for `$ne: null` to report the same kind of error.

My rationale is that if we have full boolean expression support, then `field $ne null` would be equivalent to `NOT( field $eq null)`, while the inner predicate in the latter is not supported.

**Comment by tatu-at-datastax** [comment]
Looks like Documents API might be implementing "$exists" different from REST API -- to me, Doc API got it right, whereas REST API, as per #1518 seems to consider it an alias for "booleanField $EQ true" which does not seem very useful.

Not sure what to do about that but noting this as relevant.
