### ISSUE TITLE
Count of the number of documents in the collection and subdocuments

### ISSUE THREAD

**Issue by sash2222** [stargate/stargate#1098]
Counters of the number of documents in the collection and subdocuments in a specific document when using "where". Such a possibility would significantly reduce the complexity of the developed logic in cases when it is necessary to obtain the number of entities.

**Comment by dimas-b** [comment]
@sash2222 : Supporting something like `SELECT count(*)` is possible. However, I'd like to clarify that it will not work well with pagination because the data set may change between the count query and the query to fetch actual document contents. I hope this is not the use use you had in mind.

If you only need _estimates_ for the total data size #870 may be applicable too, I guess.

**Comment by dimas-b** [comment]
@sash2222 : Could you post an example URL for this feature and example expected output, please?

**Comment by semichkin** [comment]
GET .../collections/{collectionName}/?aggregations=["$count(*)"]
returns all documents count in the collection

for example, we have a next collection structure:
{
  "documentId1": {...},
  "documentId2": {...},
  "documentId3": {...},
  ...,
  "documentId100": {...}
}

and response with $count aggregation ignored max documents count in the page and returns somethink like this: 
{
  "$count": 100
}

And the for subdocuments:
{
  "documentId1": {
    "subdocument": {
      "subdocumentId1": 1,
      "subdocumentId2": 2,
      ...
      "subdocumentId100: 100
    }
  }
}

GET .../collections/{collectionName}/documentId1/subdocument/*?aggregations=["$count(*)"]
returns: 
{
  "$count": 100
}

**Comment by jeffreyscarpenter** [comment]
supported in JSON API
