### ISSUE TITLE
Allow setting operators that cause ALLOW FILTERING as unsafe/disabled

### ISSUE THREAD

**Issue by alecl** [stargate/stargate#1168]
I was surprised to see ALLOW FILTERING for queries that use the gt operator for example which typically alarms DBAs and disallowed in production in many companies.

It would be valuable to have configuration mode to disable queries that need ALLOW filtering and return a specific HTTP code and error value if they are used.

**Comment by ivansenic** [comment]
The problem here is that using the `$gt` or any other operator, needs not only to match the document leaf value being grater than required value, but also needs to match the path of the field you are searching for. That's because each JSON value in a document is mapped to a single row in C. Without the `ALLOW FILTERING` we would not be able to match the field path.

We did this with care and we are not using `ALLOW FILTERING` just as. In each query there should be an explicit usage of indexes or the partition key. If you see this is not a case, please let us know.

Disabling would simply not work, as you would not be able to use any searching functionality of the document API.

**Comment by alecl** [comment]
That's good to know. In the case of multiple WHERE clauses you are also validating that each clause is covered by a secondary index or partition key and Cassandra itself can benefit from combining multiple indexes in its search process?

I know that's the case for the optimizer in good relational databases but wasn't sure about Cassandra.

**Comment by ivansenic** [comment]
When you say multiple `WHERE` clauses you mean multiple conditions in the `where` parameter right?

There are certain situation where we can not relate to secondary index or partition key. It's when following filter ops:

* `$ne`
* `$nin`
* `$exists: false`

are used without any other filter operation combo. As these should match the documents where the given field is not existing as well, we have no chance to utilize the indexing. We load data as you would for getting all documents (without `WHERE`), and doing in-memory filtering on the Stargate side. I repeat that this is only the case when we have no other filter ops that can utilize the indexes, if this is the case, we would execute that one first and we would utilize the partition key for the above ones.

Continuing on the matter, when there are multiple filter ops in the `where` clause, we always try to optimize the expression and avoid doing any queries that do not utilize indexes and/or partition key. In addition to that, we also allow a caller to specify `$selectivity` parameter, so that a caller can specify an order to execution. This can help if you known that one of the filter ops in your query should hit smaller amount of data than another.

We are in the moment planning to write a detailed documentation on the specific of the Document API searching, including differences between filter ops, available options, etc. I would paste a link to this documentation here once it's finalized.

**Comment by jeffreyscarpenter** [comment]
JSON API addresses this differently with use of indexes
