### ISSUE TITLE
Support Computed Fields

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#121]
When defining an API, a user may want to compute a value so it doesn’t have to be computed on the front end. An example would be to compute the distance between two geo points, or return the number of cart entries in a shopping cart. A suite of common functions can be defined so developers can rely on astra apis to solve their needs.

We don't have access to UDA of UDFs in astra but we could include them in the graphql api.

**Comment by olim7t** [comment]
This sounds really complicated.

On the syntax side, we'd have to either have a field for every function, or come up with a construct that allows invoking an arbitrary function, with arbitrary parameters (some of them being columns, but also possibly scalars), and an arbitrary return type. The latter is hard because GraphQL requires strict typing.

On the execution side, we'd have to find out which parameters refer to columns and add them to the query selection, then post-process the result set to compute the function for every row.
