### ISSUE TITLE
Built-in C* aggregation functions

### ISSUE THREAD

**Issue by blerghh** [stargate/stargate#130]
A common use case is to see the number of products in a cart. The functions are min, max, avg, sum, and count

Proposed format:

```
type Cart {
  cartId: TimeUuid @PrimaryKey
  userId: Uuid
  _count(field: CartFields): Integer
  _sum_float(field: CartFields): Float
  _min_float(field: CartFields): Float
  _max_float(field: CartFields): Float
  _avg_float(field: CartFields): Float
  _sum_int(field: CartFields): BigInteger
  _min_int(field: CartFields): BigInteger
  _max_int(field: CartFields): BigInteger
  _avg_int(field: CartFields): BigInteger
}

query {
  cart(value: {pk:"pk1"}) {
    values {
       cartId
       count: _count(field: id)
    }
  }
}
```

**Comment by olim7t** [comment]
Related to #137 and #138: same issue on what to pass as the argument, handling collisions with column names...

**Comment by tomekl007** [comment]
@olim7t just to double-check, this is for the `graphql-frist` API, right?

**Comment by olim7t** [comment]
This is for CQL-first.

TTL and WRITETIME are not aggregations, I was just mentioning them because they share similarities as CQL functions. This ticket is specifically about functions like `count`, `max`, etc.

I think we need a little bit of research to refine the syntax. There are a few issues with the proposal above:

1. it requires a specific field for every (function, return type) combination. This doesn't seem very scalable in the long term, especially considering custom functions. At the very least we could take the function name as an argument:
    ```
    count: _int_function(name: "count", field: id)
    ```
    We still need one field per return type, but that's an improvement. We could go further but at the cost of type safety (e.g. return everything as strings, or a custom `Any` scalar), so I'm not sure if it's a good idea.

2. Having an enum for field names (`CartFields` in the example) sounds like a good idea at first, but it assumes that all function arguments will be field names, which is true right now but might not be forever (again, consider custom functions). Also, it's not possible to pass multiple arguments with the proposed syntax. Maybe we could go with something more generic like passing all arguments in a plain string.

**Comment by tomekl007** [comment]
1. Good suggestion regarding passing the function name as a string. I think that's a good direction.
Regarding the return type. As far as I see, all functions (`count`, `sum`, `min`, `max`, `avg`) that we want support now are operating on `numeric` values, right? The graphQL allows only two numeric types: Float and Int: 
https://graphql.org/learn/schema/#scalar-types (`Scalars.GraphQLFloat` and `GraphQLInt`). The `GraphQLBigInteger` and `GraphQLBigDecimal` are deprecated so probably we should not allow them in this API.
Having said that, it seems that we need to support only two return types. We can:
a. Generate two variants of every method: one that returns `Float` and one that returns `Integer`
b. Expand on your proposition, and accept the 3rd argument, i.e.: `isFloat`:
```
count: _any_function(name: "count", field: id, isFloat: false)

```
However, it will need to return any to have one signature for both `Float` and `Integer`.
I am yielding towards option a because it gives type-safety and does not require generating of a lot of function (only two times more than `Any` version.
Lastly, this narrowing of return types would not work for custom functions - they could return any type.
In that case, we need a field for the return type.

2. Are you referring to a case when a function takes> 1 field names? For that case, passing all fields in one argument seems reasonable, i.e:
```
count: _int_function(name: "f_1", args: "a,b")
```
Also, it seems that for V1 we need to pass only one field name, so it would be:
```
count: _int_function(name: "f_1", args: "a")
```
Then, we can evolve this API in a backward-compatible way, accepting subsequent field names after `,`

Regarding the fact that not all arguments may be field names, could you tell me more about those use-cases?
Can it be for example a custom function that takes a constant as an argument (literal)? I.e.:
```
f1: _int_function(name:"custom_f", arg: "field_a, 123")
```
In this example, 123 is a constant. However, we won't be able to guess which argument is a field name, and which one is a constant. Maybe a function can have two arguments: one for field names, and one for constants?
```
f1: _int_function(name:"custom_f", fields: "field_a", consts: "123")
```
Next, we can use them to propagate to a `custom_f`. One caveat: the `custom_f` would need to accept firstly fields and then const as arguments.

wdyt?

**Comment by olim7t** [comment]
> all functions (count, sum, min, max, avg) that we want support now are operating on numeric values

True, but *CQL* numeric types, so in addition to `GraphQLInt`, `GraphQLFloat` (CQL double), we also have our own from `CustomScalars`: `BIGINT`, `DECIMAL`, `VARINT`, `FLOAT`, `SMALLINT`, `TINYINT`.

I'm OK with limiting ourselves to numeric types for now, but we need to handle any CQL type later. Something like `isFloat` could not be generalized.

> Generate two variants of every method: one that returns `Float` and one that returns `Integer`

Yes, we won't be able to avoid that I think. More like N variants per my comment above.

> Are you referring to a case when a function takes > 1 field names? For that case, passing all fields in one argument seems reasonable

Yes, I'm referring to more than one argument, and I agree that passing a comma-separated string sounds reasonable.

> Can it be for example a custom function that takes a constant as an argument (literal)?

Yes, if you have a custom function `sum(int, int)` you can call it like `SELECT sum(age, 10)...`. Or even `sum(1,1)` (although that doesn't make much sense).

> However, we won't be able to guess which argument is a field name, and which one is a constant

The CQL parser does. We just need to implement the same parsing rules in our code.

But that part doesn't need to be done right now, as long as it can be added later in a backward-compatible way (and I think a comma-separated list fulfills that requirement), we can limit ourselves to a single column for the aggregation functions now.

**Comment by tomekl007** [comment]
One more question regarding the API. Maybe an array of `[String]` would be better than just plain string with, ``?
Then, the query would be:
```
   count: _count(fields: ["id"])
```
instead of:
```
   count: _count(fields: "id")
```
wdyt?

I also have a couple of questions regarding the implementation side. As far as I understand, all aggregation functions should be generated dynamically in our code, and they won't be pre-defined in the graphQL schema, is that right?
However, in our integration tests, a query without known fields cannot be compiled, and java class cannot be generated out of it. For example:
```
query GetOrdersWithCount($value: OrdersInput, $fields: String) {
    Orders(value: $value) {
        pageState
        values {
            id
            prodId
            prodName
            customerName
            address
            description
            price
            sellPrice
            count: _count(fields: [id])
        }
    }
}
```
will not compile because of:
```
[ERROR] Can't query `_count` on type `Orders`
```
For the purpose of the test, I should just extend the schema of Orders type with the new count function, right?

**Comment by olim7t** [comment]
> Maybe an array of `[String]` would be better than just plain string with `,`?

Agreed, that's cleaner than splitting a string ourselves. For single-argument functions it's just an extra pair of braces, no big deal.

> As far as I understand, all aggregation functions should be generated dynamically in our code, and they won't be pre-defined in the graphQL schema, is that right?

No, everything has to be defined in the schema, GraphQL has no mechanism to generate code dynamically.

With everything we've discussed so far, it should look something like:
```
  count: _int_function(name: "count", args: ["id"])
```
So the `Orders` type would need to have an `_int_function` field in the schema.

**Comment by tomekl007** [comment]
@olim7t I've created a corresponding `QueryBuilder` ticket https://github.com/stargate/stargate/issues/907 for creating those aggregations. You did mention that you can help with that. Are you able to work on it so that we can do both things in parallel? Otherwise, I can handle both of those tasks.
