### ISSUE TITLE
Persistence API exposes Utf8Type as `varchar` instead of `text`

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#1499]
Stargate V1 REST API's "list all User Defined Types" seems to apply a translation to fields of type `text` and return them as `varchar`. Although these 2 types are generally interchangeable (see https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/cql_data_types_c.html or https://stackoverflow.com/questions/17530230/cassandra-text-vs-varchar) it seems better to return `text` if type is declared as `text`: especially since "cqlsh" (and Astra CQL console) both report these fields as "text" for both `text` and `varchar` declarations.

**Comment by olim7t** [comment]
It's not specific to the REST API, the issue originates in the persistence layer:

[Conversion.TYPE_MAPPINGS](https://github.com/stargate/stargate/blob/master/persistence-dse-6.8/src/main/java/io/stargate/db/dse/impl/Conversion.java#L145-L158) is what we use to decode internal types. To build it we iterate over `Column.Type` constants, and use `marshalTypeName` as the map key.  Both `text` and `varchar` correspond to the marshal type `o.a.c.db.marshal.Utf8Type`, and `varchar` happens to be declared last.

There are two ways to address the issue:
1. move the declaration of `Column.Type.Text` after `Column.Type.Varchar` in the enum, with a comment explaining why. This is the most straigthforward.
2. eliminate `Column.Type.Varchar` altogether, and make sure that `varchar` gets parsed into `Column.Type.Text` wherever types can be provided as strings (that's what we did in the Java driver). That's the best solution IMHO, but a bit more risky and a minor break of the Persistence API.

**Comment by tatu-at-datastax** [comment]
I agree with the assessment. It seems to be that on short term, option (1) makes most sense, in some form.

I wonder if there is a way to change the logic in creation of mapping to use first match, instead of last, to define winner.
That's no less arbitrary and needs to be documented. But would prevent change from having effect in other places (if order of enum entries was significant for other use cases).

**Comment by tatu-at-datastax** [comment]
Unfortunately approach (1) fails with an obscure errors during system initialization:

```
	Caused by: java.lang.IllegalArgumentException: Unknown type id: 10
		at com.datastax.oss.protocol.internal.response.result.RawType.decode(RawType.java:71)
		at com.datastax.oss.protocol.internal.response.result.RowsMetadata.decode(RowsMetadata.java:227)
		at com.datastax.oss.protocol.internal.response.result.DefaultRows$SubCodec.decode(DefaultRows.java:84)
		at com.datastax.oss.protocol.internal.response.Result$Codec.decode(Result.java:79)
		at com.datastax.oss.protocol.internal.FrameCodec.decode(FrameCodec.java:336)
		at com.datastax.oss.driver.internal.core.protocol.FrameDecoder.decode(FrameDecoder.java:88)
		at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:332)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
```

as it looks like somewhere within protocol handling by `RawType`, the "real" type to use is its `Varchar` value; there is no `Text` in `primitiveIds` array.

So I don't think I can use this approach easily. Will check per-driver mapping set up instead.

**Comment by olim7t** [comment]
I think I missed something, the marshal type is not obtained from the enum but via `ColumnUtils.toInternalType`. It might be related to the order of `ColumnUtils.CODECS`.

**Comment by tatu-at-datastax** [comment]
Ok.

A funny sidenote: we have THREE instances of `ColumnUtils` class within codebase (or maybe more but IDE shows 3) :)

**Comment by olim7t** [comment]
> java.lang.IllegalArgumentException: Unknown type id: 10

OK, I see what's happening: there is indeed no code 10 in the native protocol specification. It existed in [v2](https://github.com/apache/cassandra/blob/cassandra-2.0/doc/native_protocol_v2.spec#L526), but was removed in [v3](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v3.spec#L596), to eliminate the duplication. Only varchar=13 remains. But to add to the confusion, the default textual representation that was chosen for CQL is "text".

Stargate only supports v3+, so I'm not sure why it even has `Column.Type.Text`. We definitely never receive code 10 from clients (since it doesn't exist), and I don't think the code is used anywhere else.

What we really did in the Java driver is expose something called `TEXT` for familiarity with CQL, but internally it's [using the varchar code 13](https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/api/core/type/DataTypes.java#L48). I had forgotten this detail.

I think we should remove `Column.Type.Text`, and possibly rename `Column.Type.Varchar` to `Text`, or at least ensure that it always gets formatted as `text` when we return it in textual form to clients.

**Comment by tatu-at-datastax** [comment]
Thank you @olim7t that makes sense then; related PR makes sense to me but let's see what other Stargate team members think.
