### ISSUE TITLE
`ExecuteBatchStreamingTest` fails sporadically for the C* 4.0

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#1679]
Unfortunately, the gRPC test `ExecuteBatchStreamingTest.manyStreamingBatch` fails sporadically even after merging the https://github.com/stargate/stargate/pull/1661. Seems that two retries are not enough and that we can hit the situation that both retries also fail. 
I don't see any other solution, than to increase the number of retries. We might leave it being limited, but maybe 2 is too less.

**Comment by ivansenic** [comment]
@mpenick what do you think?

**Comment by ivansenic** [comment]
@tatu-at-datastax I think since we are using the direct executor in gRPC, there must not be any thead blocks.. So no this is not an option..

**Comment by mpenick** [comment]
I guessed I need to understand why it's being invalidated so much that it's returning unprepared so often. Is that something that can be fixed?

**Comment by mpenick** [comment]
I see: https://github.com/apache/cassandra/blob/cassandra-4.0.3/src/java/org/apache/cassandra/cql3/QueryProcessor.java#L580-L583

So if the same statement is prepared at the same time either one of those checks could fail because of a simultaneous eviction. This is not ideal, but I think the way to fix this is to synchronize prepares, at least in gRPC, so that it reduces the chance of eviction.

**Comment by tatu-at-datastax** [comment]
@mpenick Wow. That cache handling logic is seriously convoluted, with fixes wrt keyspace/no-keyspace cases and all. It is difficult to trust that to work for all cases...

But if that is to be retained (which for performance I assume needs to), instead of global sync lock it is probably possible to split lock into N different ones on module of hash code.

**Comment by mpenick** [comment]
> But if that is to be retained (which for performance I assume needs to), instead of global sync lock it is probably possible to split lock into N different ones on module of hash code.
