### ISSUE TITLE
Define maximum `page-size` in `stargate_claims` in JWT

### ISSUE THREAD

**Issue by caniko** [stargate/stargate#2049]
I need this feature for client-side operations, but I expect it to be useful, for frameworks such as RBP, on server-side as well.

The field could be `x-stargate-max-page-size`

I am using the [REST read endpoint](https://stargate.io/docs/stargate/1.0/develop/dev-with-rest.html#read-data), I think the feature should be extended to other read endpoints in addtion.

**Comment by ivansenic** [comment]
Wait I don't get why would the page size be in the JWT itself, why not having it as a query parameter when calling REST? Is the idea to define the page size per token?

I have to say that this would be very hard to accomplish. Mainly because how the authentication is done at the moment, the HTTP APIs are not doing anything wrt the authentication. Thus any token-based operation when request comes in is impossible. And the authentication service that verifies the token has no way to limit the page size, as that was already defined by the query fired by the HTTP API.

I guess you will need to solve this on your side. Meaning you can add additional information to the OAuth2 access token outside of the JWT itself. Then you can read this on the client side and set the query parameter accordingly.

**Comment by caniko** [comment]
I think extending the JWT to include features like this would be benefitial considering they can be used for dDOS attacks against the service in their current state. This decision-making is putting the burden of security and QoS on upstream projects.

I am not convinced that it is a lot of work. It is all about adding another field to the auth token, and reading that field on a per read request basis.

**Comment by ivansenic** [comment]
OK let me correct myself, it's hard to accomplish for the Stargate V2, V1 could be doable cause authentication subject is available during the rest call and claim could be easily read. And we are releasing the beta version of the V2 this week. Not sure if enabling this for V1 only makes sense.

But you are right, I will pass this issue to team discussions.

**Comment by caniko** [comment]
Thank you for the clarification! V2 seems like a regression, `stargate-claims` is essential for my project

**Comment by tatu-at-datastax** [comment]
@caniko The issue is not that we wouldn't want to carry over features but rather whether they are (easily) supportable due to major re-architecting of the system: in V2 system is no longer monolithic as services (like REST API) run separate from direct data access (coordinator/bridge). Authorization is something that is bit of cross-cutting concern, and access to JWT information will change from service perspective.

Given that this is not an existing feature, it makes sense to consider the new architecture, especially since we probably do not want to add new features on V1 (monolithic Stargate), or at least not ones that could only be implemented there -- that would be bad (having v1-only things that do not port over).

**Comment by tatu-at-datastax** [comment]
@caniko Also: maybe explaining bit more in detail the use case would help. JWT part of functionality, expected/common flow of settings is an area that the dev team is not very familiar with at this point.

**Comment by caniko** [comment]
I made an [issue](https://github.com/stargate/docs/issues/201) with regards to my usecase a while back, hope it is sufficient. This matter is very important to me, please don't hesitate to ask any follow-up questions.

**Comment by jeffreyscarpenter** [comment]
@caniko just to clarify, are you asking for the ability to set a different maximum page size for each user, that is set in a JWT? 

I ask because @tatu-at-datastax recently opened an issue to make the maximum page size for the REST API configurable via a system property, #2042. Would this address what you are looking for?

**Comment by caniko** [comment]
@jeffreyscarpenter this is nice, but I also have admin users who I would like to make exempt from the rule.
