### ISSUE TITLE
Move common and shared configuration to the `quarkus-common` `application.yaml`

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2159]
In the https://github.com/stargate/stargate/pull/2158 @kathirsvn added a `application.yaml` file and seems this is picked up the way.. So we should actually transfer all the common props to the `quarkus-common` project, instead of having it duplicated in API projects..

**Comment by tatu-at-datastax** [comment]
Yes, this is good: I knew this worked as it was used for test (re)configuration:

sgv2-quarkus-common/src/test/resources/application.yaml

but it is good idea to also use it for production settings to reduce duplication.

It is interesting of course that this works and we probably need to be careful to NOT add yaml file for any other helper libraries (if we add more) since order of merging might be arbitrary.
I assume API-provided yaml files can override settings defined in common.

**Comment by ivansenic** [comment]
I am taking this as it's needed for few projects that depend on the common.
