### ISSUE TITLE
Should we change gRPC handling of Cassandra `CONFIG_ERROR` to use Server-side error code, not Client?

### ISSUE THREAD

**Issue by tatu-at-datastax** [stargate/stargate#2253]
It looks like currently we map Cassandra persistence failures of type `CONFIG_ERROR` into HTTP Response 412 ("Precondition failed") which suggests failure is due to something client did. But looking at where these errors originate in Cassandra it looks like these are database configuration issues which are not something client has any control over.

So we should probably map these into one of server-side error codes (500 and above). There isn't anything particularly specific but we could use either very generic `500` (Internal Server error) or perhaps `503` (“The server is unavailable to handle this request right now”).

One benefit of this change is that due to the general rule that 4xx failures are only reported to the client (and not logged) these failures might be unreported right now; change would make them more visible.
But it should also be cleaner for clients.

**Comment by ivansenic** [comment]
@jeffreyscarpenter Can this be relevant to you wrt `PRECONDITION_FAILED` errors you are seeing?

**Comment by jeffreyscarpenter** [comment]
I don't think this is related, because in both locations in which the `ExceptionHandler` class returns a `FAILED_PRECONDITION`, it logs underlying exception at `ERROR` log level, and I have not been able to find any such statements in the logs.

these are the two locations:
https://github.com/stargate/stargate/blob/main/grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java#L150-L153
https://github.com/stargate/stargate/blob/main/grpc/src/main/java/io/stargate/grpc/service/ExceptionHandler.java#L224-L236

All the other cases in which the gRPC module returns `FAILED_PRECONDITION` are in the `ValuesHelper` [class](https://github.com/stargate/stargate/blob/main/grpc/src/main/java/io/stargate/grpc/service/ValuesHelper.java), and it does not appear any of these are logged (as `ERROR` or otherwise). This is what has led me to expect that the failed calls we are observing are due to badly formatted data rather than a server error.

**Comment by ivansenic** [comment]
You can not find anything in the log because those two places where just added recently.

**Comment by tatu-at-datastax** [comment]
Correct, latest code with improved logging has not yet been deployed.

**Comment by tatu-at-datastax** [comment]
Ok, I am not 100% sure my initial thinking is correct. Looks like passing invalid Data Center id for keyspace creation does -- as an example -- throws `ConfigurationException` and get mapped to CONFIG_ERROR:

```
org.apache.cassandra.exceptions.ConfigurationException: Unrecognized strategy option {dc1} passed to NetworkTopologyStrategy for keyspace ks3
```

(side note: exception message is rather cryptic here :-( )

**Comment by tatu-at-datastax** [comment]
Given that this is an actual client failure (passing wrong Datacenter, for example), no immediate work on changing type wrt HTTP response. May revisit with more specific use case or problem; closing for now.
