### ISSUE TITLE
REST tests should not create a keyspace for each test method

### ISSUE THREAD

**Issue by ivansenic** [stargate/stargate#2326]
* Create a keyspace at least for each test class instead
* Delete the created keypsace after test is done
* Tests could extend the `CqlEnabledIntegrationTestBase` so we have a single class that manages session and keyspace creation

**Comment by tatu-at-datastax** [comment]
Is this really worth the effort, refactoring existing tests, including change of base class?
I can see the need/benefits of cleaning up keyspaces (as per #2321 for docs api, fixed via #2324) but I think there may be simpler changes to achieve this instead of trying to make REST tests look like Docs API tests.

I'll think about how to avoid creating and leaving tons of keyspaces and updated this

**Comment by tatu-at-datastax** [comment]
Ok, I think that PR #2341 should work well enough: vast majority of IT test classes now create just a single keyspace, and a small number that need per-test creation should not be a major problem. As importantly in both cases keyspaces are now created after test/class is complete; I copied that from Docs API IT base class.
