### ISSUE TITLE
GraphQL: Add support for tuple type

### ISSUE THREAD

**Issue by jorgebay** [stargate/stargate#233]
We should add support for CQL tuples in GraphQL.

**Comment by olim7t** [comment]
👍 
GraphQL does not have a native tuple type, and we can't use a list because there would be no way to constrain a particular type for each element. I think the simplest approach would be a custom object type with generated field names, like `{ field0: 1, field1: "foo" }`. Similar to what I'm doing for UDTs in #126.

One specificity of tuples is that you can only omit trailing values, e.g. for `<int, text, float>`, `(1, "foo")` and `(1)` are both valid values, but `(1, 1.0)` isn't. We can't enforce that through the schema with the solution I'm proposing, but we could throw an error during the conversion.

**Comment by olim7t** [comment]
Apologies for my comment about omitting values, it was extremely confusing 🤦  What I meant was that it's possible to insert partial prefix tuples, for example a query that expects an `<int, text, float>` will also accept an `<int, text>` or `<int>`, but not an `<int, float>`.
But that's not even an issue for GraphQL since we generate a fixed data structure. The tuple literal in the generated query will always declare all the fields. Any of them can be null, no matter what its position is.
