### ISSUE TITLE
GraphQL: Use driver codecs for scalar parsing

### ISSUE THREAD

**Issue by jorgebay** [stargate/stargate#326]
Currently, graphql scalar parsing is usually more restrictive than what's allowed in CQL (i.e. `ISO-8601` instant for timestamp).

By leveraging the driver codecs, we can unify the way we parse these literals.

**Comment by olim7t** [comment]
In hindsight I'm not sure if reusing the codecs will be a good approach: the ones that are reusable as-is, such as `UuidCodec`, have very little custom logic. The ones that do interesting stuff, such as `DateCodec`, generally require their argument to be single-quoted, because that's how temporal literals work in CQL. So I would have to add the single quotes on the way in, and unquote on the way out, which is a bit ugly. I might end up duplicating the logic instead.
