### ISSUE TITLE
Add TTL on the cell mutation level and the BoundDMLQuery

### ISSUE THREAD

**Issue by tomekl007** [stargate/stargate#519]
Currently, the `BoundDMLQuery` does not carry the information about the ttl for a particular `Modification`.
We need to add this information and propagate it to the CDC producers.

**Comment by tatu-at-datastax** [comment]
@ivansenic My assumption was that it was for CDC only (based on label) -- if this is more generally applicable, sure, can re-open and just remove the label. At the same time if there is no current need, could also wait for need.

But I'll re-open this since it sounds it could be more generally useful.

**Comment by ivansenic** [comment]
I am not really sure.
