### ISSUE TITLE
Question: what should I use as the SEED param when running in Kubernetes?

### ISSUE THREAD

**Issue by jakerobb** [stargate/stargate#535]
I am working on adding Stargate to the [k8ssandra](https://github.com/k8ssandra/k8ssandra) project.

I have a Kubernetes service defined that proxies and load balances requests to all C* nodes. If I provide the DNS name of that service in the SEED envvar, the Stargate node does not show up in `nodetool status`, and I get this in the log:

```
21:04:51.081 [OptionalTasks:1] DEBUG org.apache.cassandra.db.SizeEstimatesRecorder - Node is not part of the ring; not recording size estimates
```

If I instead deploy C_, manually determine the IP address of one of my C_ pods, and then deploy Stargate using that IP for the seed, I then get:

```
21:29:11.853 [GossipStage:1] INFO org.apache.cassandra.gms.Gossiper - Node /10.28.0.12 is now part of the cluster
```

But the node still doesn't appear in `nodetool status`, so I'm not sure if that was really the problem.

What should I do? I didn't find anything helpful in the docs.

**Comment by dougwettlaufer** [comment]
Hi @jakerobb!

First off, stargate will not show up in `nodetool status` since that command is pulling members of the ring which stargate is not. Since no data is actually stored on stargate nodes themselves they do not take a portion of the token ring.

As for the SEED value, the name of the k8s service attached to C* should work, can you please provide the yaml for your service? Also, is C* already running at the time stargate is deployed?

**Comment by jakerobb** [comment]
We figured out the SEED thing -- I was providing only the namespace-local name, rather than the FQDN, for the service. With the FQDN, it works fine. Thanks!
