### ISSUE TITLE
Add "CREATE INDEX" to REST API

### ISSUE THREAD

**Issue by polandll** [stargate/stargate#580]
Currently, a user will get an error message about ALLOW FILTERING if an index, like a secondary index, is not created in CQL for a table column that is not the primary key. Add the ability to create indexes with the REST API.

**Comment by polandll** [comment]
There is a DELETE INDEX and GET INDEX as well? @dougwettlaufer

**Comment by dougwettlaufer** [comment]
There's add, delete, and get all for table.

**Comment by eribeiro** [comment]
URIs:

GET `/v2/schemas/keyspaces/{keyspaceName}/tables/{tableName}/indexes`  - retrieves all indexes for the table
POST `/v2/schemas/keyspaces/{keyspaceName}/tables/{tableName}/indexes` - creates an index for {tableName} with JSON data (below)
DELETE `/v2/schemas/keyspaces/{keyspaceName}/tables/{tableName}/indexes/{indexName}` delete an index

As for the JSON, the "column" is the only required, "kind" values must be uppercase, and "ifNotExists" defaults to false.

```json
 {
  "column": "column_name",
  "name": "index_name",
  "type": "custom index",
  "kind": "FULL/ENTRIES/KEYS/VALUES",
  "ifNotExists": [true/false]
  }
``` 

I have just figured out that it would be nice to have a "ifExists=true" query param to DELETE so that it can be a noop if the index doesn't exists. I'll open a issue and PR soon.

**Comment by jamesc127** [comment]
@eribeiro has this feature made it all the way to Astra yet?
