### ISSUE TITLE
stargate in kubernetes Cassandra baremetal

### ISSUE THREAD

**Issue by capacman** [stargate/stargate#595]
Hi,
Is there a way to run stargate in kubernetes but Cassandra on baremetal(in other network but there is no firewall)? When I try this with docker, stargate takes container address as broadcast address and gossip failing. With kubernetes it will probably same.

**Comment by jsanda** [comment]
Hi @capacman Stargate is included in [k8ssandra](https://k8ssandra.io). Take a look at the docs [here](https://k8ssandra.io/docs/topics/accessing-services/stargate/).

**Comment by dougwettlaufer** [comment]
If you could run Cassandra in the same k8s cluster as stargate that would be the easiest path forward. In order to have them running in different environments your k8s nodes and C* nodes will need to be able to connect to each other over port 7000 for gossip to work. Both the listen address and broadcast address can be set in stargate

Listen:
- starctl option `--listen`

Broadcast:
- Can be set with as a java opt `-Dstargate.broadcast_address=127.0.0.1`

A sample of the full command would be

```
JAVA_OPTS='-Dstargate.broadcast_address=X.X.X.X' ./starctl --cluster-name foo --cluster-version 3.11 --simple-snitch --listen Y.Y.Y.Y --cluster-seed Z.Z.Z.Z --enable-auth
```

**Comment by dimas-b** [comment]
The `stargate.broadcast_address` system property appears to be respected only by C* 4.0 persistence. Should we support it in C* 3.11 and DSE too?

**Comment by dougwettlaufer** [comment]
Probably a good idea @dimas-b. Off the top of my head I don't remember why C* 4.0 was unique.

**Comment by rchernobelskiy** [comment]
@capacman are your metal box ips reachable from kube pods? And what about vice versa?
If not, perhaps kube node ips are mutually reachable with metal boxes?

**Comment by jeffreyscarpenter** [comment]
Multiple approaches are documented here in comments. Plus we have added a helm chart in Stargate v2 (current `main` branch). Closing
