### ISSUE TITLE
Readiness check should wait for all bundles to start

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#620]
As reported in #617 `GET /checker/readiness` may report 200 (ok) before all the bundles are started.

This is problematic because some services may still be unavailable at that time and may still be consuming system resources for their own bootstrap activities.

The readiness check should probably report OK only when all services are up (or at least all known services).

Note: we may be able to use OSGi bundle meta-data to flag "important" services.

**Comment by dougwettlaufer** [comment]
Perfect world each bundle would expose it's own liveness and readiness checks and then in the health checker we just iterate over all of them, invoking their check. At least that was my vision when initially writing the `health-checker` but I'm not sure of the feasibility.

I do like the idea of flagging "important" services. It would also be nice if we could expose query params so that users could define what modules constitute "ready" or "live" (e.g. if you're not using restapi then you don't care if it's up).

**Comment by dimas-b** [comment]
Yes, I too was leaning towards having a "checker" interface for each bundle to implement. I'll give it a try.

**Comment by dimas-b** [comment]
Related issue: #631
