### ISSUE TITLE
Automatically reload seeds from DNS when unable to connect to storage nodes

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#710]
This issues is the Stargate counter-part of https://github.com/k8ssandra/k8ssandra/issues/411

In k8s environments storage node address may change but Stargate is usually configured with a DNS name for seeds. 

Stargate needs to reload seed addresses from DNS automatically in case it is not able to connect to any (old) seed addresses.

**Comment by jsanda** [comment]
Any update on when this might get implemented? It is more problematic in backup/restore scenarios. k8ssandra currently supports restoring to the same cluster. The default behavior has been changed to shutdown all C* nodes until the restore operation completes. This means that Stargate has to be restarted which for is a manual and somewhat error-prone process. I say it is error-prone because the user has to have the understanding of when exactly to restart Stargate.

**Comment by ds-steven-matison** [comment]
+1.  Bumped into this today.    Thanks @jsanda for sharing the root cause.
