### ISSUE TITLE
HTTP code for PUT has to be 201 when document is created

### ISSUE THREAD

**Issue by mvandenbrink** [stargate/stargate#741]
I noticed that the HTTP code on a successful creation of a document is 200 and not 201 when the HTTP method PUT is used. When HTTP POST method is used and a document is created, the HTTP code is 201. Please consider to always use HTTP code 201 when a document is created. REST standards allows to use POST and PUT method for creating resources. When a resource is created the default HTTP response code is 201, it shouldn't matter which HTTP method is used to create the resource.  In this way you can have more control whether a document was created or modified.

**Comment by EricBorczuk** [comment]
Hello again @mvandenbrink,

Thanks for the post, really appreciate the feedback! It turns out that this was an intentional decision; I will explain.

One of the main ways that we kept latencies on the low side is by avoiding "read before write" patterns - which would mean that Stargate does not try to check to see if the document exists already during a PUT, before doing the CQL insert statements required.  What this means is that to Stargate, there is no difference between inserting a batch with a brand new document and a supplied ID, and updating the data in a document with that same ID. The only difference between POST and PUT endpoints is that you use POST without a supplied document ID and it gets assigned for you.

I am open to changing this, but only if write latency is not significantly impacted; in other words, any solution that doesn't require reading the state of the storage nodes before performing a write would be perfect.

I agree that knowing whether the document was created or modified is important information, but in this case it is at odds with writing the document's information in a reasonable amount of time. We made the intentional decision to lean towards performance rather than ergonomics in this case, but I am curious what you think about this topic!

**Comment by mvandenbrink** [comment]
Hi Eric,

I already suspected that the write performance was the design reason to respond with a 200 for the PUT method, but in terms of RESTful design it is not right to do so in my opinion. 

I was wondering if the document is an update because the document already exists, you need to find the right rows with CQL in the table to update the data. Is the index used for that or is there another mechanism before a the attributes in a document are updated with CQL? In that case the default HTTP status could be 201 and if the key is found in the index or when CQL update is used, the HTTP status code could 200.

I could also try to look in the code, but I guess you can pinpoint it faster than me.
