### ISSUE TITLE
Make plugging custom persistence backends easier

### ISSUE THREAD

**Issue by jakubzytka** [stargate/stargate#768]
There is a number of problems if one wants to use stargate with a custom build of cassandra using a regular Starter:

1. the name of the persistence backend jar is "computed" from the `dse` flag and `clusterVersion`. Using a custom jar means it needs to be renamed to fit with this implementation detail
1. clusterVersion must parse as a number (why?), so versions like 4.0-beta5 are not possible (minor nuisance, but why?)
1. only `DsePersistence` and `CassandraPersistence` are valid persistence ids. Allowing to provide arbitrary jar and define persistence id used in that jar might be a better option
1. persistence-common depends on cassandra-3.11. How's that common with cassandra 4.0? Yet persistence-cassandra-4.0 depends on the common module anyway.
1. `CassandraPersistence` class contains a common code, but reusing it means that your persistence must be named `Apache Cassandra` - a minor nuisance, but relevant considering the rights of using the trademarks etc.

**Comment by dimas-b** [comment]
@jakubzytka : Would you mind splitting this into a separate issue?

> persistence-common depends on cassandra-3.11. How's that common with cassandra 4.0? Yet persistence-cassandra-4.0 depends on the common module anyway.

It might be quite a bit more involved than the other points, so it would not more convenient to track it separately.

**Comment by dougwettlaufer** [comment]
Hi @jakubzytka a lot going on here so let's unpack it


> 1. the name of the persistence backend jar is "computed" from the dse flag and clusterVersion. Using a custom jar means it needs to be renamed to fit with this implementation detail

Yes, this is a convention that we put in place to avoid requiring yet another config option. 

> 2. clusterVersion must parse as a number (why?), so versions like 4.0-beta5 are not possible (minor nuisance, but why?)

The clusterVersion parses as a number because we intend to really only work in major.minor versions (and honestly just major would be preferred). If you notice, our C* 4.0 is on a beta tag but we refer to it as just `persistence-cassandra-4.0` rather than `persistance-cassandra-4.0-beta4`

> 3. only DsePersistence and CassandraPersistence are valid persistence ids. Allowing to provide arbitrary jar and define persistence id used in that jar might be a better option

We could refactor this
https://github.com/stargate/stargate/blob/master/stargate-starter/src/main/java/io/stargate/starter/Starter.java#L335

to allow for other values but only one persistence jar is loaded at a time so it doesn't really matter. Previously when we were loading multiple jars `stargate.persistence_id` made sense to pick which one to use but at this point it can probably be removed.

> 4. persistence-common depends on cassandra-3.11. How's that common with cassandra 4.0? Yet persistence-cassandra-4.0 depends on the common module anyway.

As @dimas-b suggested, can you please log a separate issue on this and we'll get it addressed? So far we've gotten lucky that building against 3.11 and running against a different version works but we need to fix this before we get a nasty break.

> 5. CassandraPersistence class contains a common code, but reusing it means that your persistence must be named Apache Cassandra - a minor nuisance, but relevant considering the rights of using the trademarks etc.

Are you referring to `io.stargate.db.cassandra.impl.CassandraPersistence` in persistence-cassandra-4.0? This is named as such because it's built on OSS C*. On the other hand `io.stargate.db.dse.impl.DsePersistence` uses "DataStax Enterprise" because it's built on top of DSE. If you are adding different functionality and would like a different name we would suggest adding your own class that extends `io.stargate.db.datastore.common.AbstractCassandraPersistence`.

**Comment by jakubzytka** [comment]
wrt 1.

> Yes, this is a convention that we put in place to avoid requiring yet another config option.
`--dse` is used to
1. compute jar name (not needed)
2. compute `persistence_id` (not needed)
3. set a persistence-backend-specific option `emulate_dbaas_defaults`; persistence-backend-specific options should be persistence-backend-specific, and not elevated to the level of stargate. Stargate should not interpret them, but pass them to relevant persistence backend.
Ergo, it doesn't look like a valid stargate option

`--cluster-version` is used to compute jar name (not needed)
So it doesn't look like a valid stargate option either.

From what you are saying an option to pass name of the persistence backend jar is not needed. It would be enough to just load the persistence backend jar that's available.

wrt 5.:

> Are you referring to io.stargate.db.cassandra.impl.CassandraPersistence in persistence-cassandra-4.0? This is named as such because it's built on OSS C*. On the other hand io.stargate.db.dse.impl.DsePersistence uses "DataStax Enterprise" because it's built on top of DSE. If you are adding different functionality and would like a different name we would suggest adding your own class that extends io.stargate.db.datastore.common.AbstractCassandraPersistence.

That's true and I'm aware of that. The problem with this is that such approach requires copy-pasting these common parts when creating a separate, not much changed persistence backend.
However, I understand that this is not your problem until an another persistence backend gets introduced to stargate.

**Comment by dougwettlaufer** [comment]
Sorry, I'm not quite following the first point. I admit that in hindsight `emulate_dbaas_defaults` probably didn't need to be a top-level option but `--dse` and `--cluster-version` belong. From a user standpoint they shouldn't need to know anything about jars or really backends. To get started you just need to choose between DSE and C* and then the version that's compatible with your cluster.

**Comment by dimas-b** [comment]
From my POV the discussion about `--dse` and `--cluster-version` leans towards providing a custom `Starter` sub-class in @jakubzytka 's use case. From Stargate OSS perspective I do not think we can reasonably figure out the right persistence to load based on `starctl` options if we do not expose persistence implementation names. Some external knowledge is required, hence custom `Starter`.

**Comment by dimas-b** [comment]
By the way, I started working on #730 ... If it goes well, it should help to remove some of the issues with class loading an jar dependencies.

**Comment by jeffreyscarpenter** [comment]
This was partially addressed in Stargate v2.1
