### ISSUE TITLE
Bad request, use ALLOW FILTERING

### ISSUE THREAD

**Issue by john-gress** [stargate/stargate#772]
If I set up a table with some time-value pairs, both time and value are big integers, and then **I want to get a range of time, is there a way to do that through the REST API?**

With the GET request I'm using (see below), I'm getting a "Bad request ... use ALLOW FILTERING" response, with some warnings about performance. 

**How do you use "ALLOW FILTERING"?**

**And how would one know if it truly is a bad thing to do?**

For example, I set up a table with some data using the following script:
<pre><code>
#!/usr/bin/bash

export AUTH_TOKEN=$1

# Create metrics keyspace
curl -s --location --request POST 'localhost:8082/v2/schemas/keyspaces' \
   --header "X-Cassandra-Token: $AUTH_TOKEN" \
   --header 'Content-Type: application/json' \
   --data '{ "name": "metrics" }'

# Create stats table
curl -s --location --request POST localhost:8082/v2/schemas/keyspaces/metrics/tables \
   --header "X-Cassandra-Token: $AUTH_TOKEN" \
   --header "Content-Type: application/json" \
   --header "Accept: application/json" \
   --data '{ "name": "stats", "columnDefinitions": [ { "name": "stat_name", "typeDefinition": "text" }, { "name": "time", "typeDefinition": "bigint" }, { "name": "stat_value", "typeDefinition": "bigint" } ], "primaryKey": { "partitionKey": ["stat_name"], "clusteringKey": ["time"] }, "tableOptions": { "defaultTimeToLive": 0, "clusteringExpression": [{ "column": "time", "order": "DESC"}] } }'

# Create some bogus stats data
TIME=1616013100
STATNAME="Counts"

for i in {0..100}; do
   DATA=$((50000 + $RANDOM %150000))
   printf "$TIME, $DATA\n"
   curl -i -s --location --request POST 'localhost:8082/v2/keyspaces/metrics/stats' --header "X-Cassandra-Token: $AUTH_TOKEN" --header 'Content-Type: application/json' --data '{ "stat_name": "'$STATNAME'", "time": '$TIME', "stat_value": '$DATA' }'

   let TIME+=1
done
</code></pre>

When I use a GET specifying a "$lt" for the time, I get a "Bad request" response:
<pre><code>
$ curl -s -L -X GET 'http://localhost:8082/v2/keyspaces/metrics/stats?where=\{"time":\{"$lt":1616013110\}\}&page-size=5' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json" | python -m json.tool
{
    "code": 400,
    "description": "Bad request: org.apache.cassandra.stargate.exceptions.InvalidRequestException: Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
}
</code></pre>

**Comment by dougwettlaufer** [comment]
Since `stat_name` is your partition key it needs to be included in your request because the entire primary key (stat_name + time) must be provided. The other option is to create an index on `time`.

https://stargate.io/docs/stargate/1.0/developers-guide/rest-using.html#_read_data
> The primary key of the table can be used in the WHERE clause, but non-primary key columns cannot be used unless indexed.


@polandll do you have any plans for docs related to the `ALLOW FILTERING` message?

**Comment by john-gress** [comment]
Thanks @dougwettlaufer!

This works:
<pre><code>
$ curl -s -L -X GET 'http://localhost:8082/v2/keyspaces/metrics/stats?where=\{"stat_name":\{"$eq":"Counts"\},"time":\{"$lt":1616013110\}\}&page-size=5' -H "X-Cassandra-Token: $AUTH_TOKEN" -H "Content-Type: application/json" | python -m json.tool
</code></pre>

With regard to setting up an index on `time`, it looks like the docs are saying the only way to do that is through CQL. There is no REST API for that. Correct?

**Comment by eribeiro** [comment]
This somewhat relates to https://github.com/stargate/stargate/issues/766 and I am okay with closing it if you think it's not worth providing a way of pass ALLOW FILTERING to the query.

**Comment by john-gress** [comment]
I see the relationship, but I'm still wondering about:

How do you use "ALLOW FILTERING" through the REST API?

And how would one know if it truly is a bad thing to do?

**Comment by polandll** [comment]
Yes - I have not gotten the messaging about INDEXES into all API docs yet, but I will add a specific WARNING about ALLOW_FILTERING so that people find the indexing information.

**Comment by polandll** [comment]
@john-gress  -- In Cassandra, the partition key must be used to retrieve data. If you don't include it, Cassandra tells you that you can use an option to use ALLOW_FILTERING. However, that option is only appropriate for early exploration, and is basically a flag that your query is ill-formed and that you should think about how to query the table differently. 

In REST and GraphQL API, ALLOW_FILTERING would truly be bad, because essentially, it's always truly bad. The answer is that you can create indexes for columns that you want to query that are not a partition key. But too many indexes are also a bad practice, and you want to make indexes only for the columns that you will use in queries. 

Additionally, you cannot create indexes in REST, but you can create them in CQL or GraphQL. Once created, REST queries can include those columns that are indexed.

Here is how you can create GraphQL indexes. (This is how I create them, so that I can call a curl command in scripts that are testing rest queries.)
The mutation:
mutation createIndexes {
  book: createIndex(
    keyspaceName:"library",
    tableName:"book",
    columnName:"author",
    indexName:"author_idx",
  )
}
And the curl for that:
curl --location --request POST {base_url}{base_gql_schema} \
--header "X-Cassandra-Token: {auth_token}" \
--header 'Content-Type: application/json' \
--data-raw '{"query":"mutation createIndexes {\n  book: createIndex(\n    keyspaceName:\"library\",\n    tableName:\"book\",\n    columnName:\"author\",\n    indexName:\"author_idx\",\n )\n }","variables":{}}'

**Comment by eribeiro** [comment]
Hi @john-gress,

> How do you use "ALLOW FILTERING" through the REST API?

AFAIK, this is not possible today. Adding a "filtering=true" query param is the goal of #766.
 If I read the code right this is the line that would need to change: https://github.com/stargate/stargate/blob/1aca10b974498dd9047e7d2e8f754621f9785092/restapi/src/main/java/io/stargate/web/resources/v2/RowsResource.java#L575-L585 **The problem is that the user can easily shoot herself/himself in the foot by using filtering.**
> And how would one know if it truly is a bad thing to do?

Poor performance. And filtering efficiency depends on how many rows and how much filtering Cassandra will need to do. It looks like using filtering is frown upon as a Cassandra anti-pattern that even if available should be sparingly used and only if strictly necessary. @polandll recommendations are really great and should be used instead, I guess.

Disclaimer: Please, take my explanation with a grain of salt 'cause I don't have the knowledge and experience of @polandll and @dougwettlaufer.

**Comment by john-gress** [comment]
@eribeiro - thanks for your help clarifying these issues.
