### ISSUE TITLE
`contains` and `containsEntry` don't seem to work when conjuncted in the REST API (NOT documents)

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#819]
In this example:
`{"text_map": {"$contains": "a"}, "text_map": {"$contains": "b"}}`

Only the latter filter gets honored and used. In this example:
`{"text_map": {"$contains": "a", "$contains": "b"}}`

Again, only the latter is honored.

Is this a problem with only contains? Or is it a problem with all conjuncted filters?

**Comment by polandll** [comment]
I am interested in the outcome of this investigation, too. I have doc examples of multiple where items, and to be truthful, I don't know if they are working as Ram found or not.

**Comment by eribeiro** [comment]
> Is this a problem with only contains? Or is it a problem with all conjuncted filters?

**The problem is the use of duplicate keys in JSON (e.g., `{"key1": 3, "key1": 73}`) and how WhereParser deals with it.** 

**The JSON standard doesn't make any mention of duplicate keys being invalid or valid nor what to do in such cases**, so it's up to the JSON libraries available for each language to decide what to do when facing this situation. 

The JSON linter I used the most (https://jsonlint.com/) flags any JSON with duplicate key as invalid (see picture below).
<img width="1108" alt="Screen Shot 2021-04-03 at 11 23 16" src="https://user-images.githubusercontent.com/116156/113481331-42ec5f80-946f-11eb-867b-860a54207aad.png">

Following the same pattern, a library could raise an exception when presented with duplicate keys, but libraries like Jackson (Java) and json (Python) sort of convert the JSON structure to a (nested) Map and dict, respectively. 

So, when you have something like `{"key1": 3, "key1": 73}` Jackson would roughly do something like this:

```
Map<String, Integer> map = new HashMap<>();
map.put("key1", 3);
map.put("key1", 73);

// map == {'key1: 73}
```

See? You are overriding the first key-value with the second one. This is exactly what @EricBorczuk called _"latter filter gets honoured"_. 🙂 The first thing `WhereParser#parseWhere` does is to convert the JSON String to an object tree so it will automatically "de-deduplicate" the keys as exemplified above.

**What would be a good compromise then?**

In theory, it's possible to do some Jackson hacking to allow duplicate keys but this can lead to complex parsing code in `WhereParser#parseWhere`, subtle corner cases, and unintuitive behaviour, IMHO.

Still Taking Eric's example as a guideline, I think the best way to represent those JSON predicates would be:
`{"text_map": {"$contains": ["a", "b"}}` or `{"text_map": [{"$contains": "a"}, {"$contains": "b"}]}`. The latter is valid because `text_map` key points to a list of objects each with its own key-value pair while I still prefer the former for reasons of readability, more concise representation, and simplifying the parsing logic used by `WhereParser#parseWhere`.

For supporting a syntax as `{"text_map": {"$contains": ["a", "b"}}`, `WhereParser#parseWhere` requires the fix proposed in  https://github.com/stargate/stargate/issues/639, but not only that. 

> Is this a problem with only contains? Or is it a problem with all conjuncted filters?

I am still not 100% sure, but after some late night code inspection `$contains`, `$containsEntry`, `$containsKey` and `$eq` are the affected one and require code changes to be properly supported, I guess. As for `$in` we could have ``{"field": {"$in": [1, 2], "$in": [3, 4]}}`` but rewriting it as a sane JSON (i.e., `{"field": {"$in": [1, 2, 3, 4]}}`) is already supported.

**Comment by polandll** [comment]
I like the syntax `{"text_map": {"$contains": ["a", "b"]}}`. I had considered  nested operators like:
`{"text_map":{"$containsKey": {"$in": "a", "b"}}} in trying to think about how it could work. So that's somewhat consistent.

**Comment by eribeiro** [comment]
I have a branch with a refactoring (practically a rewrite) of `WhereParser` and it supports `{"text_map": {"$contains": ["a", "b"]}}` syntax as well as it fixes one or two subtle bugs not being tested in the `WhereParser` as of today. I can submit as PR if you wish to take a look. :)

**Comment by eribeiro** [comment]
I am gonna write a couple of more tests and open a PR, so we advance the discussion. :)

**Comment by eribeiro** [comment]
@olim7t Hi, maybe you can find this PR worth reviewing and merging. 🙂

**Comment by eribeiro** [comment]
@polandll and  Ram Palagummi: I have a candidate PR to address the syntax we have been discussing. It's pending review and approval, but if it gets accepted then the examples below will be accepted syntax:

`{"text_map": {"$contains": "a"}}`
`{"text_map": {"$contains": ["a", "b"]}}`
`{"text_map": {"$containskey": ["a", "b"]}}`
`{"text_map": {"$containskey": "a"}}`
`{"text_map": {"$containsentry": [{"key": "a", "value": "1"}, {"key": "b", "value": "2"}]}}`
`{"text_map": {"$containsentry": {"key": "a", "value": "1"}}`

**Comment by rampalagummi** [comment]
@dougwettlaufer @eribeiro : I tried the above format in Astra Serverless and none of them are working. Has the fix been published to Astra Serverless?
