### ISSUE TITLE
Batched up POST to create multiple rows with the REST API

### ISSUE THREAD

**Issue by EricBorczuk** [stargate/stargate#821]
It would be nice to have a new endpoint in the REST V2 API to create multiple rows in a table at once!

**Comment by eribeiro** [comment]
@EricBorczuk Hi Eric, how are you doing? :) 

I'd love to implement this, but I have some questions concerning the use of C* unlogged/logged batches, that was the first thing that came to my mind when thinking about this and https://github.com/stargate/stargate/issues/586. Googling it a bit, it seems like something that shouldn't be used unless strictly necessary and it's even seen as an anti-pattern because it would put too much stress on the coordination node. Eric, I see that you sort of have batches already implemented on the Docs API, so I would really like to hear your opinions on the subject of sending batch inserts to the DB.

**Comment by dougwettlaufer** [comment]
@eribeiro I'm not sure if we necessarily need batches do we? Couldn't the request be broken into N inserts as well? Also, I'd suggest making this either async or setting an aggressive threshold to avoid timeouts and potential for missed inserts.

**Comment by shridharsheth** [comment]
@EricBorczuk I second what @dougwettlaufer said. It's about saving on multiple POST calls and network latency incurred because of that. I also wonder if Stargate has enough of table schema to group by partition key and then use unlogged batches (by partition) to further save on Stargate -> Cassandra times as well. That solution will avoid putting unnecessary pressure on single coordinator node.

**Comment by caniko** [comment]
As an alternative to save bandwidth, the JSON should have a map for identical columnar values for the respective batch (DRY).

**Comment by caniko** [comment]
@shridharsheth @eribeiro, I don't understand why the implementation has to put load on a single cassandra coordinator. Shouldn't there be some sort of _load balancing_ for cassandra coordinators on the Stargate side?

**Not an expert** in the field - you are fully welcome to ridicule me for having this opinion - the feedback to this feature request seems a little _lackluster_.

**Comment by dougwettlaufer** [comment]
> @shridharsheth @eribeiro, I don't understand why the implementation has to put load on a single cassandra coordinator. Shouldn't there be some sort of load balancing for cassandra coordinators on the Stargate side?

@caniko Stargate is functioning as the Cassandra coordinator and is being load balanced by whatever ingress you're using. So if you make N restapi requests they will be load balanced across M different Stargate instances. The problem is if you send a large batch in a single request then only a single Stargate instance (aka Cassandra coordinator) will pick up the request thus causing more load on one of the coordinators than on the others. Now is this any worse than running a `BATCH` in CQL? Probably not.

Really this is a tradeoff of evenly distributing load across Stargate instances (N requests) or reducing the amount of calls from your client (1 request containing N inserts).

**Comment by caniko** [comment]
Thanks for making the problem clearer.

Can't I just break up my batch into smaller batches, and send them to several Cassandra coordinators?

**Comment by dougwettlaufer** [comment]
> The problem seems to be easily solved by breaking up the batch into smaller batches.

Sure, that works too.

**Comment by shridharsheth** [comment]
@caniko @dougwettlaufer The reason I mentioned table schema in my previous comment was because I was thinking about splitting an insert request with multiple rows received by a Stargate instance to multiple INSERT statements to Cassandra DB. I believe that efficient way to do that would be to batch them by primary key if logged batch needs to be used.
If multiple statements to Cassandra are generated without using a BATCH, failure scenarios will have to be managed such that calling client gets clear information on which rows succeeded vs. failed.

**Comment by caniko** [comment]
How is the load balancing ensured when using GraphQL? Asking because it seems like it supports batching (according to the docs).

https://stargate.io/docs/stargate/1.0/quickstart/quick_start-graphql.html#_insert_data
