### ISSUE TITLE
Optionally provide further info about query execution in REST API

### ISSUE THREAD

**Issue by eribeiro** [stargate/stargate#823]
It would be nice if there was a "query info" (info=true) option in the REST API as below:

`http://localhost:8082/v2/keyspaces/k1/t1?where={"id":{"$eq":"John"}, "age":{"$eq": 45}}&info=true`

```json
{
	"count": 0,
	"data": [],
	"queryInfo": {
		"cqlQuery": "SELECT id, age, \"firstName\", \"lastName\" FROM \"k1\".\"t1\" WHERE id = ? AND age = ?",
		"tableName": "t1",
		"partitionKeys": ["[acc67a74-e7c2-4416-9b9d-8fd79515b8c1]"],
		"columns": ["id", "age", "firstName", "lastName"],
		"numRows": 0,
		"consistencyLevel": "LOCAL_QUORUM",
		"keyspace": "k1",
                "queryTimeInMs": 46 
	}
}
```

This would make easier to clients to check the CQL query that really hits the DB, its execution time, besides other things.

**Comment by eribeiro** [comment]
Wdyt @dougwettlaufer ?

**Comment by dougwettlaufer** [comment]
If we do it would definitely need to default to false. With all of our HTTP services we're really trying to abstract away the idea of CQL in order to make C* more palatable to new users.

I would suggest that the `queryInfo` object only contain
* query
* partitionKeys
* consistencyLevel
* queryTimeInMs

These are in the request itself so not super useful to return
* tableName
* keyspace

These are already in the response
* columns
* numRows

**Comment by eribeiro** [comment]
Got it. Thanks. 

PS: Yes, definitely it would default to false.
