### ISSUE TITLE
Question -  Stargate Support with WCF Or .Net Api

### ISSUE THREAD

**Issue by ImAbhishekTomar** [stargate/stargate#841]
Hi,

Currently i have lot of WCF api and as per the new company guideline i need to migrate these in Stargate, can you please help and let me know that Stargate support WCF and if you have any sample code repo please share.

Thanks!!

**Comment by dougwettlaufer** [comment]
Hi @ImAbhishekTomar, I'm not familiar with WCF would you mind providing a link? Also could you describe a little more about what you're trying to accomplish? Do you have an existing application calling WCF which you would like to move to REST?

**Comment by ImAbhishekTomar** [comment]
What is WCF - https://docs.microsoft.com/en-us/dotnet/framework/wcf/whats-wcf
Get started -https://docs.microsoft.com/en-us/dotnet/framework/wcf/getting-started-tutorial
Sample Code - https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/getting-started-sample

WCF is a Microsoft architecture for creating API.

**Comment by dougwettlaufer** [comment]
Sorry to be dense but I'm still not quite sure I follow (I've never touched .NET). 

As of now Stargate exposes CQL, Graphql, and REST interfaces which means on the client side if you want to use REST then you'd use your rest client of choice and make requests to Stargate with that. There's nothing fancy, you'd integrate with it as you would any other REST service. Now if you're looking at it from the other side, we don't expose WCF. If this is something you'd like to implement we'd be happy to help you although I'm not sure how this would work since stargate is written in java.

**Comment by ImAbhishekTomar** [comment]
https://github.com/Kong/kong/issues/7095
