### ISSUE TITLE
The bundle state liveness check should return "OK" unless there are errors

### ISSUE THREAD

**Issue by dimas-b** [stargate/stargate#934]
Currently Stargate performs two checks as part of the "liveness" probe (used by k8s):

1. It checks that all OSGi bundles are `ACTIVE`
1. It checks that schema agreement is achievable.

The seconds check (schema) will return "OK" even if Stargate is in schema disagreement, but schema sync tasks are still running.

However, the first check (bundles) will not return "OK" until the process is _fully_ started, which can take considerable time.

As [discussed](https://github.com/k8ssandra/k8ssandra/issues/654#issuecomment-834583270) in https://github.com/k8ssandra/k8ssandra/issues/654 it makes sense to adjust the bundle check to report "OK" unless some bundles _fail_ to start. In other works the bundle check should be "OK" during the bootstrapping process unless it does observe a specific error.

**Comment by ivansenic** [comment]
As wrote in k8ssandra/k8ssandra#654 let's introduce the startup probe better.

**Comment by dimas-b** [comment]
Technically the `Starter` class supports watching jars for changes on disk, so conceivably bundles can change state in runtime.

I'd be +1 on dropping support for on-the-fly bundle changes, though.

**Comment by ivansenic** [comment]
> > As wrote in [k8ssandra/k8ssandra#654](https://github.com/k8ssandra/k8ssandra/issues/654) let's introduce the startup probe better.
> 
> Which check do you see going into startup only? Things like schema and datastore connectivity need to be ran continuously to catch any issues that pop up but the bundle check _might_ be okay to run once? I'm not sure if there's something that could cause a bundle to crash mid run.

I was not pointing which checks should go for the startup, but rather to change the current approach with `readiness + liveness` with `startup + liveness`. 

The reason is that readiness and liveness are independent from each other. This is why the current k8s setup has a long delay of starting probes, like 180 sec. It means that the pod can go up and than wait until readiness kicks in to move the pod to ready state. And we can not decrease the delay for readiness probe without decreasing the delay for the liveness probe, as then you can end up in situation where no liveness check is done for the difference in delay. And if we decrease both, then we end up in problem that liveness probe can restart the pod before it's actually even ready.

With startup probe we would solve this, we can start running startup probe with the short delay, as liveness probe only goes into action when startup probe has confirmed that it's green. Meaning we have no problem anymore with the delays, liveness starts once the pod is declared as started (ready).

What goes into both probes is up for discussion, but I don't see a need for a difference from exactly current checks. But with the change to startup probe we would solve the problem @dimas-b originally opened the ticket for.

**Comment by jsanda** [comment]
>If we signal that stargate is live too early then that could result in failed requests.

In Kubernetes it could actually be the opposite. If you wait too long signal liveness, like say after schema agreement, then Kubernetes could kill the Stargate container before startup completes.

**Comment by dougwettlaufer** [comment]
> @dougwettlaufer I was not pointing which checks should go for the startup, but rather to change the current approach with `readiness + liveness` with `startup + liveness`.

Okay, misunderstood. I got it now.

**Comment by dimas-b** [comment]
I think it would be nice to keep the `readiness` check even if we always return `OK` for now. It might be handy in case we want to manage incoming traffic based on Stargate load, for example (in the future).

**Comment by jsanda** [comment]
Just so you are aware, k8ssandra currently is not using startup probes since we support earlier versions of Kubernetes.

**Comment by ivansenic** [comment]
I could not find the Kubernetes 1.16 API reference, so I am not sure if the `startupProbe` is available there or not. Furthermore, I just saw it became stable in 1.20, and in earlier versions it's enabled by a feature flag. So I guess this is off the table.

**Comment by dimas-b** [comment]
From the Stargate's perspective we could still add a `startup` HTTP endpoint. It will be user's choice whether to call it or not. Some environments may have newer k8s versions.

**Comment by jeffreyscarpenter** [comment]
Should we keep this open @ivansenic ?
